# Copyright IBM Corp. 2013, 2026
# SPDX-License-Identifier: MPL-2.0

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[deps] : "
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[deps] : "
    groups:
      go:
        patterns:
          - "*"
