# Copyright IBM Corp. 2013, 2026
# SPDX-License-Identifier: MPL-2.0

version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - forbidigo
    - govet
    - ineffassign
    - modernize
    - unparam
    - unused
    # - errcheck
    - staticcheck

  settings:
    forbidigo:
      # Forbid the following identifiers (list of regexp).
      forbid:
        - pattern: \brequire\.New\b(# Use package-level functions with explicit TestingT)?
        - pattern: \bassert\.New\b(# Use package-level functions with explicit TestingT)?
        - pattern: \bmetrics\.IncrCounter\b(# Use labeled metrics)?
        - pattern: \bmetrics\.AddSample\b(# Use labeled metrics)?
        - pattern: \bmetrics\.MeasureSince\b(# Use labeled metrics)?
        - pattern: \bmetrics\.SetGauge\b(# Use labeled metrics)?
      # Exclude godoc examples from forbidigo checks.
      # Default: true
      exclude-godoc-examples: false
  exclusions:
    rules:
    # Temp Ignore SA9004: only the first constant in this group has an explicit type
    # https://staticcheck.io/docs/checks#SA9004
      - linters:
          - staticcheck
        text: 'SA9004:'
      # - linters:
      #     - staticcheck
      #   text: 'SA1019: Package github.com/golang/protobuf/jsonpb is deprecated'
      # - linters:
      #     - staticcheck
      #   text: 'SA1019: Package github.com/golang/protobuf/proto is deprecated'
      # - linters:
      #     - staticcheck
      #   text: 'SA1019: ptypes.MarshalAny is deprecated'
      # - linters:
      #     - staticcheck
      #   text: 'SA1019: ptypes.UnmarshalAny is deprecated'
      # - linters:
      #     - staticcheck
      #   text: 'SA1019: package github.com/golang/protobuf/ptypes is deprecated'

formatters:
  settings:
    gofmt:
      simplify: true
