language: go

go:
  - 1.4
  - tip

install: make deps

script:
  - make test

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#serfdom"
    skip_join: true
    use_notice: true

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
