name: Build

on:
  pull_request:
  push:
    branches:
      - master

# This workflow runs for not-yet-reviewed external contributions and so it
# intentionally has no write access and only limited read access to the
# repository.
permissions:
  contents: read

jobs:
  build:
    name: "Build binary"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'oldstable'
          - 'stable'
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go toolchain
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: "Build binary"
        run: make dev
