name: Checks

on:
  pull_request:
  push:
    branches:
      - master

# This workflow runs for not-yet-reviewed external contributions and so it
# intentionally has no write access and only limited read access to the
# repository.
permissions:
  contents: read

jobs:
  lint:
    name: "Run golangci-lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'oldstable'
          - 'stable'
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Go toolchain
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: "go.mod and go.sum consistency check"
        run: make tidy

      - name: Lint code
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2

  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'oldstable'
          - 'stable'
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Go toolchain
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: "Unit tests"
        run: |
          go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: coverage.out
          name: coverage-report-${{ matrix.version }}

      - name: Display coverage report
        run: go tool cover -func=coverage.out

  unit-tests-race:
    name: "Unit Tests Race"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'oldstable'
          - 'stable'
    steps:
      - name: "Fetch source code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Go toolchain
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: "Race Unit tests"
        run: |
          go test -race ./serf/...
